[build]
	command = "npx turbo run build --filter=@connected-repo/frontend"
  publish = "apps/frontend/dist"

[build.environment]
	NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
