import { ExpirationPlugin } from 'workbox-expiration';
import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing'
import {NetworkFirst} from 'workbox-strategies'

declare const self: ServiceWorkerGlobalScope;

// Clean up old caches from previous versions
cleanupOutdatedCaches();

// Inject the precache manifest (generated by the plugin)
precacheAndRoute(self.__WB_MANIFEST);

// Listen for SKIP_WAITING message from the app
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    (self as ServiceWorkerGlobalScope).skipWaiting();
  }
});

//Network first implementation for caching all the api requests to backend
registerRoute(
	({url}) => url.origin === import.meta.env.VITE_API_URL && url.pathname.startsWith("/api/"),
	new NetworkFirst({
		cacheName: "api-cache",
		plugins: [
			new ExpirationPlugin({
				maxEntries: 50,
				maxAgeSeconds: 60 * 60 * 24 * 7, // one week
			}),
		]
	}),
	"GET"
);

// Offline fallback for navigation (SPA routing)
registerRoute(
  new NavigationRoute(createHandlerBoundToURL('/index.html'))
);