import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing'

declare const self: ServiceWorkerGlobalScope;

// Clean up old caches from previous versions
cleanupOutdatedCaches();

// Inject the precache manifest (generated by the plugin)
precacheAndRoute(self.__WB_MANIFEST);

// Listen for SKIP_WAITING message from the app
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    (self as ServiceWorkerGlobalScope).skipWaiting();
  }
});

// Offline fallback for navigation (SPA routing)
registerRoute(
  new NavigationRoute(createHandlerBoundToURL('/index.html'))
);